/**
 * ServiceLineage — provenance of a Service generated by a sb-style cascade.
 *
 * Each Service published to the catalog carries a {@link ServiceLineage} so
 * downstream consumers (verify-time replay, mint-side analytics, audit) can
 * trace the cell / ICP / hypothesis / studio thesis the Service originated
 * from, plus the cascade run that produced it and the version vector of all
 * inputs.
 *
 * All fields are loose-typed (string refs) at this layer — `WorkContextCellRef`,
 * `IcpContextProblemRef`, `FoundingHypothesisRef`, `StudioThesisRef` are
 * sb-internal Nouns whose canonical types ship from `business.org.ai` /
 * `startup-builder` later. Until then, they're {@link string} aliases so this
 * type compiles without a circular dependency.
 *
 * @packageDocumentation
 */

// ============================================================================
// Loose ref aliases — replaced by typed Noun refs once sb lands those types
// ============================================================================

/** Reference to a `WorkContextCell` Noun (sb-internal). */
export type WorkContextCellRef = string

/** Reference to an `IcpContextProblem` Noun (sb-internal). */
export type IcpContextProblemRef = string

/** Reference to a `FoundingHypothesis` Noun (sb-internal). */
export type FoundingHypothesisRef = string

/** Reference to a `StudioThesis` Noun (sb-internal). */
export type StudioThesisRef = string

// ============================================================================
// Version vector
// ============================================================================

/**
 * Version snapshot of every input that contributed to a Service generation.
 *
 * Fields are placeholders pending the canonical version-vector shape from
 * sb's cascade-event substrate. Each value is an opaque version string
 * (semver, content-hash, or commit SHA depending on subsystem).
 */
export interface VersionVector {
  /** Version of the ontology graph (`business.org.ai` snapshot). */
  ontology: string
  /** Version of the cascade engine that ran the generation. */
  engine: string
  /** Version of the generation prompts / templates. */
  generation: string
  /** Version of the founding hypothesis at generation time. */
  fh: string
}

// ============================================================================
// ServiceLineage
// ============================================================================

/**
 * Provenance record attached to a generated Service.
 *
 * `cellRef` / `icpContextProblemRef` / `foundingHypothesisRef` are the three
 * sb cascade roots; `studioThesisRef` is present only for Services minted
 * inside a studio context. `cascadeRunId` identifies the specific run that
 * produced this Service so verify-time replay can re-emit identical events.
 * `versionVector` snapshots all inputs at generation time.
 */
export interface ServiceLineage {
  cellRef: WorkContextCellRef
  icpContextProblemRef: IcpContextProblemRef
  foundingHypothesisRef: FoundingHypothesisRef
  /** Present when the Service was minted inside a studio context. */
  studioThesisRef?: StudioThesisRef
  cascadeRunId: string
  versionVector: VersionVector
}
